#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t cm"

$L "Welcome to Android `getprop ro.build.version.release` / `getprop ro.modversion`";
$L " ";
$L "                                 _/_/            _/";
$L "    _/_/    _/_/_/  _/_/      _/        _/_/_/  _/_/_/";
$L " _/    _/  _/    _/    _/  _/_/_/_/  _/    _/  _/    _/";
$L "_/    _/  _/    _/    _/    _/      _/    _/  _/    _/";
$L " _/_/    _/    _/    _/    _/        _/_/_/  _/_/_/";
$L "                                        _/";
$L "                                   _/_/";
$L " ";
